
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Pack;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DOSPUNTOS = 35;
  public static final int WHEN = 16;
  public static final int FUNCTION = 3;
  public static final int OPSUM = 26;
  public static final int STR = 40;
  public static final int PUT = 36;
  public static final int OPDEC = 29;
  public static final int ELSIF = 11;
  public static final int INT = 23;
  public static final int OUT = 22;
  public static final int FOR = 12;
  public static final int AND = 17;
  public static final int IS = 5;
  public static final int IN = 21;
  public static final int OR = 18;
  public static final int GET = 37;
  public static final int BEGIN = 6;
  public static final int OPREL = 33;
  public static final int NUM = 38;
  public static final int EXIT = 15;
  public static final int LOOP = 14;
  public static final int IF = 8;
  public static final int ID = 39;
  public static final int PARIZQ = 30;
  public static final int BOOLEAN = 24;
  public static final int EOF = 0;
  public static final int RETURN = 4;
  public static final int TRUE = 19;
  public static final int error = 1;
  public static final int COMA = 34;
  public static final int ELSE = 10;
  public static final int WHILE = 13;
  public static final int FLOAT = 25;
  public static final int THEN = 9;
  public static final int END = 7;
  public static final int OPASG = 28;
  public static final int PARDER = 31;
  public static final int FALSE = 20;
  public static final int OPMULT = 27;
  public static final int PROCEDURE = 2;
  public static final int PYC = 32;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PROCEDURE",
  "FUNCTION",
  "RETURN",
  "IS",
  "BEGIN",
  "END",
  "IF",
  "THEN",
  "ELSE",
  "ELSIF",
  "FOR",
  "WHILE",
  "LOOP",
  "EXIT",
  "WHEN",
  "AND",
  "OR",
  "TRUE",
  "FALSE",
  "IN",
  "OUT",
  "INT",
  "BOOLEAN",
  "FLOAT",
  "OPSUM",
  "OPMULT",
  "OPASG",
  "OPDEC",
  "PARIZQ",
  "PARDER",
  "PYC",
  "OPREL",
  "COMA",
  "DOSPUNTOS",
  "PUT",
  "GET",
  "NUM",
  "ID",
  "STR"
  };
}

