
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Pack;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 6;
  public static final int PARDER = 5;
  public static final int error = 1;
  public static final int PARIZQ = 4;
  public static final int OPSUM = 2;
  public static final int OPMULT = 3;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "OPSUM",
  "OPMULT",
  "PARIZQ",
  "PARDER",
  "NUM"
  };
}

